language: php
php:
  - 7.0
  - 7.1
sudo: false
before_install:
  - phpenv config-rm xdebug.ini
install:
  - composer install
services:
  - mysql
before_script:
  - mysql -e 'create database app;'
script:
  - vendor/bin/phpunit
